spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/carrefour_one?currentSchema=pm_voucher_engine
    username: ecarrefour
    password: ecarrefour
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8199
  error:
    include-stacktrace: always
